# Generated by Django 3.1.1 on 2020-09-10 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BF&E', 'Business, Finances & Economics'), ('CS&T', 'Computers, Science & Technology'), ('EA&C', 'Entertainment, Art & Culture'), ('GN', 'General News'), ('H&M', 'Health & Medicine'), ('Sports', 'Sports')], max_length=31)),
                ('title', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
